export const SESSION_OPEN_BOTTOM_MAX_WAIT_MS = 3_500;
export const USER_SUBMIT_BOTTOM_MAX_WAIT_MS = 6_000;
export const SESSION_LAYOUT_STABLE_MS = 80;
export const SCROLL_ANCHOR_IDLE_CAPTURE_MS = 140;
export const USER_SCROLL_RESIZE_RESTORE_SUPPRESS_MS = 260;
export const USER_SCROLL_ANCHOR_RESTORE_SUPPRESS_MS = 700;
export const MAX_RESIZE_ANCHOR_RESTORE_PX = 300;
